version: '3'

services:
    db:
        container_name: smartranking
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: pass123
            POSTGRES_DB: smartranking
            POSTGRES_USER: labrancax
            PGDATA: /var/lib/
        tty: true

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin

        ports:
            - '8080:80'
        tty: true
